version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - postgres
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@root.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - postgres
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - '5050:80'

networks:
  postgres:
    driver: bridge

volumes:
  db:
    driver: local
  pgadmin:
    driver: local
